name: Build

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-26.04, macos-26, macos-26-intel]
        arch: [x64, arm64]
        exclude:
          - os: windows-2025
            arch: arm64
          - os: ubuntu-26.04
            arch: arm64
          - os: macos-26
            arch: x64
          - os: macos-26-intel
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - if: startsWith(matrix.os, 'windows')
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.arch }}
      - if: startsWith(matrix.os, 'windows')
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja

      - if: startsWith(matrix.os, 'ubuntu')
        uses: egor-tensin/setup-gcc@v2
        with:
          version: 13
          platform: ${{ matrix.arch }}
      - if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install meson ninja
          sudo apt install libx11-dev libx11-xcb-dev libwayland-dev cairo

      - if: startsWith(matrix.os, 'macos')
        run: |
          brew install meson ninja
          echo "CC=$(brew --prefix llvm@20)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@20)/bin/clang++" >> $GITHUB_ENV

      - if: startsWith(matrix.os, 'windows')
        run: meson setup build --buildtype release -Dprefix="$pwd\install"
      - if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: meson setup build --buildtype release -Dprefix="$(pwd)/install"
      - run: meson compile -C build rye
      # :TODO: run tests
      - run: meson install -C build --no-rebuild

      - if: startsWith(matrix.os, 'windows')
        run: Compress-Archive -Path install\bin\rye.exe, install\bin\*.dll -DestinationPath RYE-${{ runner.os }}-${{ matrix.arch }}.zip

      - if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
          cd install/bin
          tar cfz RYE-${{ needs.create-release.outputs.tag }}-${{ runner.os }}-${{ matrix.arch }}.tar.gz *

  push-staging:
    needs: run-tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push staging branch to trunk
        if: github.event_name == 'push'
        run: git switch trunk && git merge --ff-only staging && git push origin trunk
