name: Build

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-26.04, macos-26, macos-26-intel]
        arch: [x64, arm64]
        exclude:
          - os: windows-2025
            arch: arm64
          - os: ubuntu-26.04
            arch: arm64
          - os: macos-26
            arch: x64
          - os: macos-26-intel
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
      - if: startsWith(matrix.os, 'windows')
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja

      - if: startsWith(matrix.os, 'ubuntu')
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
          platform: ${{ matrix.arch }}
      - if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install meson ninja

      - if: startsWith(matrix.os, 'macos')
        run: |
          brew install meson ninja
          echo "CC=$(brew --prefix llvm@20)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@20)/bin/clang++" >> $GITHUB_ENV

      - run: meson setup build --buildtype debugoptimized
      - run: meson compile -C build rye
      # - run: run tests

  push-staging:
    needs: run-tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push staging branch to trunk
        if: github.event_name == 'push'
        run: git switch trunk && git merge --ff-only staging && git push origin trunk
